apiVersion: apps/v1
kind: Deployment
metadata:
  name: echolocal-app
  namespace: echolocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echolocal-app
  template:
    metadata:
      labels:
        app: echolocal-app
    spec:
      containers:
      - name: echolocal
        resources:
          limits:
            cpu: 2m
            memory: 0.5Gi
          requests:
            cpu: 2m
            memory: 0.5Gi
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 8000
