apiVersion: v1
kind: Service
metadata:
  name: echolocal-app-service
  namespace: echolocal
spec:
  selector:
    app: echolocal-app
  ports:
    - protocol: TCP
      port: 80
      name: tcp-80
      targetPort: 8080
    - protocol: TCP
      port: 3000
      name: tcp-3000
      targetPort: 3000
  type: LoadBalancer
