apiVersion: v1
kind: Service
metadata:
  name: echolocal-app-service
  namespace: echolocal
spec:
  selector:
    app: echolocal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
