name: TEST, Build and Push

on:
  push:
    branches: [main]

env:
  ARTIFACT_REGISTRY: ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: echolocal-images
  IMAGE: echolocal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Packages preparation
        run: yarn install

      - name: "TESTs time ;)"
        run: yarn test

  build-and-push-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag $ARTIFACT_REGISTRY/$REPOSITORY/$IMAGE:$GITHUB_SHA

      - name: Push image
        run: docker push $ARTIFACT_REGISTRY/$REPOSITORY/$IMAGE:$GITHUB_SHA
