name: TEST, Build, Push and Deploy

on:
  push:
    branches: [main]

env:
  ARTIFACT_REGISTRY_URL: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY_NAME: echolocal-images
  IMAGE: echolocal
  GKE_CLUSTER: echolocal-cluster
  DEPLOYMENT_NAME: echolocal-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Packages preparation
        run: yarn install

      - name: "TESTs time ;)"
        run: yarn test

  build-push-deploy-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PREACT_APP_API_URL: ${{ secrets.API_URL }}
          file_name: .env
          fail_on_empty: true
          sort_keys: false

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag $ARTIFACT_REGISTRY_URL/$REPOSITORY_NAME/$IMAGE:$GITHUB_SHA

      - name: Push image
        run: docker push $ARTIFACT_REGISTRY_URL/$REPOSITORY_NAME/$IMAGE:$GITHUB_SHA

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ secrets.GCP_REGION }}

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          # curl -sLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.1/kustomize_v5.0.1_linux_amd64
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          # replacing the image name in the k8s template
          ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=$ARTIFACT_REGISTRY_URL/$REPOSITORY_NAME/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl -n echolocal rollout status deployment/$DEPLOYMENT_NAME
          kubectl -n echolocal get services -o wide
